### ISSUE TITLE
Successful alliance upload doesn't notify user or clear old error message

### ISSUE THREAD

**Issue by Techno11** [lethosor/TBA-uploader#22]
When uploading alliances, I got an error message for a connection timeout.  However, when the upload did successfully go through, the error message showing the failed connection didn't go away, and there was no obvious notification that the upload went successfully other than me opening the network tab and seeing the successful request.

**Comment by lethosor** [comment]
Good catch, missed part of the (pretty clunky) pattern I'm using for error handling in other places.
